# Generated by Django 5.2.17 on 2026-10-01 10:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('name', 'location'), name='uniq_centre_name_location')],
            },
        ),
        migrations.CreateModel(
            name='CentreTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centre_tests', to='catalog.centre')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centre_tests', to='catalog.diagnostictest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('centre', 'test'), name='uniq_centre_test'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='centretest_price_positive')],
            },
        ),
    ]
